inverted_index_folder = 'indexes/inverted_index'
indexed_urls_file = 'indexes/indexed_urls.txt'  # used to check which URLs have been indexed already
forward_index_folder = 'indexes/forward_index'
forward_index_folder = 'indexes/forward_index'
frequencies_file = 'indexes/frequencies.bin'    # stores the frequency of each word in a separate file for autocomplete
processed_docs_file = 'indexes/processed'       # used for retrieving document data given doc id
lexicon_file = 'indexes/lexicon.csv'
ids_file = 'indexes/next_ids.txt'
dataset_file = '30_articles.csv'
scraped_file = 'indexes/scraped'
texts_file = 'indexes/texts'
